#!/usr/bin/env python3
"""
Final Solution: Configure IOS Device for Modern SSH Algorithms
==============================================================

Since NSO's Java SSH client doesn't support legacy KEX algorithms,
we need to configure the IOS device to support modern algorithms.
This script provides the configuration commands needed.
"""

print('=' * 70)
print('SOLUTION: Configure IOS Device for Modern SSH Algorithms')
print('=' * 70)
print()
print('PROBLEM:')
print('  - IOS device only supports: diffie-hellman-group14-sha1')
print('  - NSO Java SSH (JSch) doesn\'t support legacy SHA-1 algorithms')
print('  - Connection fails during KEX negotiation')
print()
print('SOLUTION:')
print('  Configure the IOS device to support modern SSH algorithms')
print('  This must be done via console or another management method')
print()
print('=' * 70)
print('IOS DEVICE CONFIGURATION COMMANDS')
print('=' * 70)
print()
print('Connect to iosv-dcloud via console or another method, then run:')
print()
print('configure terminal')
print('ip ssh server algorithm kex diffie-hellman-group14-sha256')
print('ip ssh server algorithm kex ecdh-sha2-nistp256')
print('ip ssh server algorithm kex ecdh-sha2-nistp384')
print('ip ssh server algorithm kex ecdh-sha2-nistp521')
print('ip ssh server algorithm kex curve25519-sha256')
print('ip ssh server algorithm kex curve25519-sha256@libssh.org')
print('ip ssh version 2')
print('ip ssh time-out 120')
print('ip ssh authentication-retries 3')
print('end')
print('write memory')
print()
print('=' * 70)
print('ALTERNATIVE: If device doesn\'t support modern algorithms')
print('=' * 70)
print()
print('If the IOS version is too old to support modern algorithms,')
print('you have these options:')
print()
print('1. Upgrade IOS to a version that supports modern SSH algorithms')
print('2. Use a different management method (SNMP, HTTP, etc.)')
print('3. Use an SSH proxy/gateway that supports both old and new algorithms')
print('4. Configure NSO to use a different SSH client (not recommended)')
print()
print('=' * 70)
print('VERIFICATION')
print('=' * 70)
print()
print('After configuring, verify SSH algorithms:')
print('  show ip ssh')
print()
print('Then test connection from NSO:')
print('  devices device iosv-dcloud connect')
print('  devices device iosv-dcloud ssh fetch-host-keys')
print('=' * 70)
