#!/usr/bin/env python3
"""
Check what SSH algorithms the IOS device is actually offering
=============================================================

Since the device is configured with diffie-hellman-group14-sha256
but NSO still can't connect, we need to verify what algorithms
the device is actually advertising.
"""

print('=' * 70)
print('Troubleshooting: Device Already Configured with Modern Algorithm')
print('=' * 70)
print()
print('The device is configured with:')
print('  ip ssh server algorithm kex diffie-hellman-group14-sha256')
print()
print('But NSO still can\'t connect. Possible issues:')
print()
print('1. Device might still be offering OLD algorithms as well')
print('   Solution: Disable old algorithms explicitly')
print()
print('2. NSO Java SSH might not support diffie-hellman-group14-sha256')
print('   Solution: Check NSO/Java SSH supported algorithms')
print()
print('3. Device might need additional configuration')
print('   Solution: Check if other SSH settings are needed')
print()
print('=' * 70)
print('ADDITIONAL CONFIGURATION TO TRY')
print('=' * 70)
print()
print('If the device is still offering old algorithms, try:')
print()
print('configure terminal')
print('no ip ssh server algorithm kex diffie-hellman-group14-sha1')
print('no ip ssh server algorithm kex diffie-hellman-group-exchange-sha1')
print('ip ssh server algorithm kex diffie-hellman-group14-sha256')
print('ip ssh server algorithm kex ecdh-sha2-nistp256')
print('ip ssh server algorithm kex ecdh-sha2-nistp384')
print('ip ssh server algorithm kex ecdh-sha2-nistp521')
print('end')
print('write memory')
print()
print('=' * 70)
print('VERIFICATION')
print('=' * 70)
print()
print('Check what algorithms the device is actually offering:')
print('  show ip ssh')
print()
print('Or test with verbose SSH:')
print('  ssh -v cisco@198.18.1.11')
print('  (Look for "kex: server->client" and "kex: client->server" lines)')
print('=' * 70)
