# Auto-generated MCP tools for example-service YANG model
# Generated by Universal YANG Model Analyzer

import ncs.maapi as maapi
import ncs.maagic as maagic
import logging

logger = logging.getLogger(__name__)
